/** Runtime 包统一出口。只导出核心构造与类型。 */
export { createRuntime } from './createRuntime'
export { CheckpointManager } from './checkpoint'
export { loadCraignore, parseCraignore } from './craignore'
export { createTraceCollector } from './trace'
export { isDebugScope, debugLog, setDebugScopes, DEBUG_SCOPES } from './debug'
export { StreamTimeoutError, withIdleTimeout, guardContext, hardTruncate, checkContext, estimateTokens, estimateTokensAccurate, estimateMessagesTokens, estimateMessageTokens, generateSummary } from '@crai/base'
export type { Summarizer, CompactionGuardOptions, GuardContextResult, ContextCheckResult } from '@crai/base'
export type { RuntimeOptions } from './createRuntime'
export { createHookBus, createEventBus } from './bus'
export type { TraceFn } from './bus'
export type { TraceEntry, TraceMode } from './trace'
